language: cpp
cache: apt

env:
  - SCCC_CONFIG=VCAN_FX15DEV
  - SCCC_CONFIG=2016_CAMERA
  - SCCC_CONFIG=2016_CCD
  - SCCC_CONFIG=2016_RAIL
  - SCCC_CONFIG=2016_MAGNETIC

before_install:
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
  - sudo apt-get update
  - sudo apt-get install gcc-arm-none-eabi --allow-unauthenticated

script: make all
